// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzeQ41KE5kvVywB1SRIUs-SnxDlUU1hkM',
    appId: '1:178468885259:web:3bfbe2b18e12064206880e',
    messagingSenderId: '178468885259',
    projectId: 'quan-ly-chi-tieu-e034d',
    authDomain: 'quan-ly-chi-tieu-e034d.firebaseapp.com',
    storageBucket: 'quan-ly-chi-tieu-e034d.firebasestorage.app',
    measurementId: 'G-DW0526PK20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR45xA6hgZYCVrqDcRUpve6QjT2-SsHMM',
    appId: '1:178468885259:android:cf73a44ecc04239e06880e',
    messagingSenderId: '178468885259',
    projectId: 'quan-ly-chi-tieu-e034d',
    storageBucket: 'quan-ly-chi-tieu-e034d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqju3Wp4ofU09ymz-kdnbJQCMG6FrmC_I',
    appId: '1:178468885259:ios:094448db282cdb1e06880e',
    messagingSenderId: '178468885259',
    projectId: 'quan-ly-chi-tieu-e034d',
    storageBucket: 'quan-ly-chi-tieu-e034d.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieuManhVinh12026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzeQ41KE5kvVywB1SRIUs-SnxDlUU1hkM',
    appId: '1:178468885259:web:28277b22e2b4db0f06880e',
    messagingSenderId: '178468885259',
    projectId: 'quan-ly-chi-tieu-e034d',
    authDomain: 'quan-ly-chi-tieu-e034d.firebaseapp.com',
    storageBucket: 'quan-ly-chi-tieu-e034d.firebasestorage.app',
    measurementId: 'G-YF2YDTWLXN',
  );
}
