// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEldHh6rsOM63m69nLSSqTwgqclpeaoQ0',
    appId: '1:92178457342:web:3621416fa93e0eb0613baf',
    messagingSenderId: '92178457342',
    projectId: 'so-thu-chi-ac609',
    authDomain: 'so-thu-chi-ac609.firebaseapp.com',
    storageBucket: 'so-thu-chi-ac609.firebasestorage.app',
    measurementId: 'G-V2DSP1475T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0Xm6XhLDJW6e1OZM8vaH5GSWaNqddRw',
    appId: '1:92178457342:android:c5399fdea3f3a586613baf',
    messagingSenderId: '92178457342',
    projectId: 'so-thu-chi-ac609',
    storageBucket: 'so-thu-chi-ac609.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZmlLlldVDGXcsXbwDC9acNUMEQ24pwcI',
    appId: '1:92178457342:ios:1407affca5654077613baf',
    messagingSenderId: '92178457342',
    projectId: 'so-thu-chi-ac609',
    storageBucket: 'so-thu-chi-ac609.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieuManhVinh12026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZmlLlldVDGXcsXbwDC9acNUMEQ24pwcI',
    appId: '1:92178457342:ios:1407affca5654077613baf',
    messagingSenderId: '92178457342',
    projectId: 'so-thu-chi-ac609',
    storageBucket: 'so-thu-chi-ac609.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieuManhVinh12026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEldHh6rsOM63m69nLSSqTwgqclpeaoQ0',
    appId: '1:92178457342:web:0439604ad5a0e53a613baf',
    messagingSenderId: '92178457342',
    projectId: 'so-thu-chi-ac609',
    authDomain: 'so-thu-chi-ac609.firebaseapp.com',
    storageBucket: 'so-thu-chi-ac609.firebasestorage.app',
    measurementId: 'G-GQC8S7DCWM',
  );
}
